version: "3.7"

services:

  front-image:

    container_name: Front

    build: ./

    volumes:

      - "/app/node_modules"

      - ".:/app"

    ports:

      - "4200:4200"

    command: >

      bash -c "npm start"